### ISSUE TITLE
Publish lab website

### ISSUE THREAD

**Issue by nniiicc** [BITS-Research/Lab#1]
Pages needed: 

- About
- Members
- Research Projects 
- Publications

**Comment by nguyen-info** [comment]
I'm familiar somewhat familiar with [Jekyll](https://jekyllrb.com/) and [Nikola](https://getnikola.com/) static site generators. Do we have a preference? I can help set up once we decide on an approach. Happy to learn about other static site generators too.

**Comment by nniiicc** [comment]
Thanks @michi-gato  ... I'll try to publish a stub later next week and we can collectively update in the future.

**Comment by nguyen-info** [comment]
I ran into [Titus Brown's lab website](http://ivory.idyll.org/lab/coc.html) and it would be neat to have a lab CoC and philosophy on our future website, as well.

**Comment by nniiicc** [comment]
Absolutely - Love this and very relevant to the type of lab model we want to replicate. Another CoE we may want to consult in developing our own is http://widgets.weforum.org/coe/#code
