### ISSUE TITLE
Accessing Riot room

### ISSUE THREAD

**Issue by nguyen-info** [BITS-Research/Lab#2]
I'm having trouble accessing [our Riot](https://riot.im/app/#/room/!SSJrQHKpuEbChJXkHi:matrix.org?via=matrix.org) with my existing account.

@nniiicc can you pls add my username to our room? @snewyuen:matrix.org 
I think that should work. Thanks!

**Comment by nniiicc** [comment]
I fixed the link in our documentation - I think this one should work for a new subscriber to the channel https://matrix.to/#/!SSJrQHKpuEbChJXkHi:matrix.org?via=matrix.org
