### ISSUE TITLE
Building a dynamic survey tool for data privacy judgements

### ISSUE THREAD

**Issue by nam14d** [BITS-Research/Lab#5]
1. Why you are interested in this research project (e.g. Do you have experience with this topic? Does it sound cool and you just want to find out more? etc.)

One reason why I initially gravitated towards this topic is because it required experience in R to help develop a survey, and I have experience with both of those topics. I understand R quite well because I am part of the Data Science specialization in the MSIM program, and I worked with Professor Fiorito to use Qualtrics and SAS to respectively distribute multiple surveys and analyze their results. Even better, after reading through the goals of the project, I am happy to say that the survey I helped create included the use of experimental vignettes; while I sadly cannot say that I designed them, I did work with assist in for various groups who would then take the survey. 
**Paper Citation**: Fiorito, Jack, and Russell, Zachary Alexander. “Voting for the Union: An Experimental Vignette Study.” Academy of Management Proceedings, vol. 2020, no. 1, 2020, p. 18105.

2. Spend 5 minutes googling some of the keywords. What did you find? What ideas or questions does this spark for you in working on this research project?

I began by looking at formr's documentation and noting how the interactive elements resemble those in Rshiny in its use of names and labels; it also serving as another output for R code probably also helps the comparison. I am curious about how it specifically flows when run by a participant because, at first glance, it looks very different to Qualtrics in terms of layout. One question that I had though was what exactly an FVS was. I looked it up, and I doubt the project is referring to a Forest Vegetation Simulator. 

3. What is your availability for working on this research? (e.g. I can devote 5-10 hours per week for the next two quarters)

As a volunteer, I could donate 10-15 hours per week until the Summer quarter. From there my availability depends on how successful (or not) I am at receiving an internship. 

4. I can meet with project coordinators at any time on October 1st or October 5th from 9-5.

**Comment by nniiicc** [comment]
Hi @nam14d - Would you be available to talk sometime soon about this project? You can reach out on the ischool slack or via email at `nmweber@uw.edu` to schedule a time. Looking forward to discussing this, and its great you have factorial vignette survey :) experience !!!
